In [ ]:
import  pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Projects/IPL(2022-2025)/IPL_2022_2025")

/tmp/ipykernel_19362/1479506071.py:3: DtypeWarning: Columns (46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/drive/MyDrive/Projects/IPL(2022-2025)/IPL_2022_2025")

In [ ]:
print(df.shape)

(70163, 65)

Checking the columns and droping them if not necessry/

In [ ]:
df.columns.tolist()

['Unnamed: 0',
 'match_id',
 'date',
 'match_type',
 'event_name',
 'innings',
 'batting_team',
 'bowling_team',
 'over',
 'ball',
 'ball_no',
 'batter',
 'bat_pos',
 'runs_batter',
 'balls_faced',
 'bowler',
 'valid_ball',
 'runs_extras',
 'runs_total',
 'runs_bowler',
 'runs_not_boundary',
 'extra_type',
 'non_striker',
 'non_striker_pos',
 'wicket_kind',
 'player_out',
 'fielders',
 'runs_target',
 'review_batter',
 'team_reviewed',
 'review_decision',
 'umpire',
 'umpires_call',
 'player_of_match',
 'match_won_by',
 'win_outcome',
 'toss_winner',
 'toss_decision',
 'venue',
 'city',
 'day',
 'month',
 'year',
 'season',
 'gender',
 'team_type',
 'superover_winner',
 'result_type',
 'method',
 'balls_per_over',
 'overs',
 'event_match_no',
 'stage',
 'match_number',
 'team_runs',
 'team_balls',
 'team_wicket',
 'new_batter',
 'power_surge_start',
 'batter_runs',
 'batter_balls',
 'bowler_wicket',
 'batting_partners',
 'next_batter',
 'striker_out']

In [ ]:
df.drop(columns=['Unnamed: 0'], inplace=True)

### Checking Duplicate:

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
dup_balls = df.duplicated(
    subset=['match_id', 'innings', 'over', 'ball']
).sum()

print(dup_balls)   # can be wides/No balls

3071

### Missing values

In [ ]:
missing = df.isnull().sum().sort_values(ascending=False)

missing_percent = (
    df.isnull().mean() * 100
).sort_values(ascending=False)

missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_percent
})

print(missing_df)

                   Missing Count   Missing %
power_surge_start          70163  100.000000
superover_winner           69901   99.626584
review_batter              69595   99.190457
umpire                     69595   99.190457
review_decision            69595   99.190457
...                          ...         ...
batter_runs                    0    0.000000
batter_balls                   0    0.000000
bowler_wicket                  0    0.000000
batting_partners               0    0.000000
striker_out                    0    0.000000

[64 rows x 2 columns]

Total Matches:

In [ ]:
df['match_id'].nunique()

293

In [ ]:
matches_per_season = (
    df.groupby('season')['match_id']
    .nunique()
    .reset_index(name='matches')
)

print(matches_per_season)

   season  matches
0    2022       74
1    2023       74
2    2024       71
3    2025       74

In [ ]:
matches_2024 = (
    df[df['season'] == 2024]['match_id']
    .unique()
)

print(len(matches_2024))
print(sorted(matches_2024))

71
[np.int64(1422119), np.int64(1422120), np.int64(1422121), np.int64(1422122), np.int64(1422123), np.int64(1422124), np.int64(1422125), np.int64(1422126), np.int64(1422127), np.int64(1422128), np.int64(1422129), np.int64(1422130), np.int64(1422131), np.int64(1422132), np.int64(1422133), np.int64(1422134), np.int64(1422135), np.int64(1422136), np.int64(1422137), np.int64(1422138), np.int64(1422139), np.int64(1426260), np.int64(1426261), np.int64(1426262), np.int64(1426263), np.int64(1426264), np.int64(1426265), np.int64(1426266), np.int64(1426267), np.int64(1426268), np.int64(1426269), np.int64(1426270), np.int64(1426271), np.int64(1426272), np.int64(1426273), np.int64(1426274), np.int64(1426275), np.int64(1426276), np.int64(1426277), np.int64(1426278), np.int64(1426279), np.int64(1426280), np.int64(1426281), np.int64(1426282), np.int64(1426283), np.int64(1426284), np.int64(1426285), np.int64(1426286), np.int64(1426287), np.int64(1426288), np.int64(1426289), np.int64(1426290), np.int64(1426291), np.int64(1426292), np.int64(1426293), np.int64(1426294), np.int64(1426295), np.int64(1426296), np.int64(1426297), np.int64(1426298), np.int64(1426299), np.int64(1426300), np.int64(1426302), np.int64(1426303), np.int64(1426305), np.int64(1426306), np.int64(1426307), np.int64(1426309), np.int64(1426310), np.int64(1426311), np.int64(1426312)]

unique team name:

In [ ]:
teams = sorted(df['batting_team'].unique())

print(teams)

['Chennai Super Kings', 'Delhi Capitals', 'Gujarat Titans', 'Kolkata Knight Riders', 'Lucknow Super Giants', 'Mumbai Indians', 'Punjab Kings', 'Rajasthan Royals', 'Royal Challengers Bangalore', 'Royal Challengers Bengaluru', 'Sunrisers Hyderabad']

In [ ]:
team_mapping = {
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru'

}

df['batting_team'] = df['batting_team'].replace(team_mapping)
df['bowling_team'] = df['bowling_team'].replace(team_mapping)
df['toss_winner'] = df['toss_winner'].replace(team_mapping)
df['match_won_by'] = df['match_won_by'].replace(team_mapping)

In [ ]:
teams = sorted(df['bowling_team'].unique())

print(teams)

['Chennai Super Kings', 'Delhi Capitals', 'Gujarat Titans', 'Kolkata Knight Riders', 'Lucknow Super Giants', 'Mumbai Indians', 'Punjab Kings', 'Rajasthan Royals', 'Royal Challengers Bengaluru', 'Sunrisers Hyderabad']

Venue checking

In [ ]:
venues = sorted(df['venue'].unique())

for v in venues:
    print(v)

Arun Jaitley Stadium, Delhi
Barsapara Cricket Stadium, Guwahati
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow
Brabourne Stadium, Mumbai
Dr DY Patil Sports Academy, Mumbai
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam
Eden Gardens, Kolkata
Himachal Pradesh Cricket Association Stadium, Dharamsala
M Chinnaswamy Stadium, Bengaluru
MA Chidambaram Stadium, Chepauk, Chennai
Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur
Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh
Maharashtra Cricket Association Stadium, Pune
Narendra Modi Stadium, Ahmedabad
Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh
Rajiv Gandhi International Stadium, Uppal, Hyderabad
Sawai Mansingh Stadium, Jaipur
Wankhede Stadium, Mumbai

In [ ]:
venue_mapping = {
    'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur':
    'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh'
}

df['venue'] = df['venue'].replace(venue_mapping)

Ball-By-Ball logic validation

In [ ]:
innings_balls = (
    df[df['valid_ball'] == 1]
    .groupby(['match_id', 'innings'])
    .size()
    .reset_index(name='legal_balls')
)

print(innings_balls.sort_values(
    by='legal_balls',
    ascending=False
).head())

     match_id  innings  legal_balls
583   1485779        1          120
0     1304047        1          120
582   1473511        2          120
2     1304048        1          120
581   1473511        1          120

In [ ]:
df['over'].describe()

count    70163.000000
mean         9.244687
std          5.682954
min          0.000000
25%          4.000000
50%          9.000000
75%         14.000000
max         19.000000
Name: over, dtype: float64

In [ ]:
innings_score = (
    df.groupby(['match_id', 'innings'])['runs_total']
    .sum()
    .reset_index()
)

print(innings_score.head())

   match_id  innings  runs_total
0   1304047        1         131
1   1304047        2         133
2   1304048        1         177
3   1304048        2         179
4   1304049        1         205

### Wicket validation

In [ ]:
wickets = (
    df[df['player_out'].notnull()]
    .groupby(['match_id', 'innings'])
    .size()
    .reset_index(name='wickets')
)

print(wickets.sort_values(
    by='wickets',
    ascending=False
).head())

     match_id  innings  wickets
557   1473501        2       10
21    1304057        2       10
534   1473487        2       10
520   1473480        1       10
524   1473482        2       10

### Player validation

In [ ]:
players = pd.concat([
    df['batter'],
    df['bowler']
]).unique()

print(len(players))

345

### Date validation

In [ ]:
df['runs_total'].describe()

count    70163.000000
mean         1.462038
std          1.742910
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max          7.000000
Name: runs_total, dtype: float64

In [ ]:
df['runs_batter'].unique()

array([0, 1, 4, 6, 2, 3, 5])

# Step 2: Making multiple table out of raw dataset

In [ ]:
ball_by_ball = df.copy()

In [ ]:
drop_cols = [

    'review_batter',
    'team_reviewed',
    'review_decision',
    'umpire',
    'umpires_call',
    'power_surge_start',
    'new_batter',
    'next_batter'
]

ball_by_ball.drop(columns=drop_cols, inplace=True)

In [ ]:
team_mapping = {
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru'

}

team_cols = [
    'batting_team',
    'bowling_team',
    'toss_winner',
    'match_won_by'
]

for col in team_cols:
    ball_by_ball[col] = (
        ball_by_ball[col]
        .replace(team_mapping)
    )

In [ ]:
venue_mapping = {
    'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur':
    'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh'
}

ball_by_ball['venue'] = (
    ball_by_ball['venue']
    .replace(venue_mapping)
)

In [ ]:
ball_by_ball['date'] = pd.to_datetime(
    ball_by_ball['date']
)

In [ ]:
def get_phase(over):

    if over <= 5:
        return 'Powerplay'

    elif over <= 14:
        return 'Middle Overs'

    else:
        return 'Death Overs'

ball_by_ball['phase'] = (
    ball_by_ball['over']
    .apply(get_phase)
)

In [ ]:
ball_by_ball['display_over'] = (
    ball_by_ball['over'] + 1
)

In [ ]:
ball_by_ball['is_boundary'] = (
    ball_by_ball['runs_batter']
    .isin([4, 6])
)

In [ ]:
ball_by_ball['is_dot_ball'] = (
    ball_by_ball['runs_total'] == 0
)

In [ ]:
# Create Legal Wicket Column
# Bowler shold not get wicket for run_out or retired_hurt



valid_bowler_wickets = [
    'bowled',
    'caught',
    'lbw',
    'stumped',
    'caught and bowled',
    'hit wicket'
]

ball_by_ball['is_bowler_wicket'] = (
    ball_by_ball['wicket_kind']
    .isin(valid_bowler_wickets)
)

In [ ]:
ball_by_ball.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70163 entries, 0 to 70162
Data columns (total 61 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           70163 non-null  int64
 1   date               70163 non-null  datetime64[ns]
 2   match_type         70163 non-null  object
 3   event_name         70163 non-null  object
 4   innings            70163 non-null  int64
 5   batting_team       70163 non-null  object
 6   bowling_team       70163 non-null  object
 7   over               70163 non-null  int64
 8   ball               70163 non-null  int64
 9   ball_no            70163 non-null  float64
 10  batter             70163 non-null  object
 11  bat_pos            70163 non-null  int64
 12  runs_batter        70163 non-null  int64
 13  balls_faced        70163 non-null  int64
 14  bowler             70163 non-null  object
 15  valid_ball         70163 non-null  int64
 16  runs_extras        70163 non-null  int64
 17  runs_total         70163 non-null  int64
 18  runs_bowler        70163 non-null  int64
 19  runs_not_boundary  70163 non-null  bool
 20  extra_type         4134 non-null   object
 21  non_striker        70163 non-null  object
 22  non_striker_pos    70163 non-null  int64
 23  wicket_kind        3584 non-null   object
 24  player_out         3584 non-null   object
 25  fielders           2729 non-null   object
 26  runs_target        33686 non-null  float64
 27  player_of_match    70163 non-null  object
 28  match_won_by       70163 non-null  object
 29  win_outcome        69467 non-null  object
 30  toss_winner        70163 non-null  object
 31  toss_decision      70163 non-null  object
 32  venue              70163 non-null  object
 33  city               70163 non-null  object
 34  day                70163 non-null  int64
 35  month              70163 non-null  int64
 36  year               70163 non-null  int64
 37  season             70163 non-null  int64
 38  gender             70163 non-null  object
 39  team_type          70163 non-null  object
 40  superover_winner   262 non-null    object
 41  result_type        696 non-null    object
 42  method             682 non-null    object
 43  balls_per_over     70163 non-null  int64
 44  overs              70163 non-null  int64
 45  event_match_no     70163 non-null  object
 46  stage              70163 non-null  object
 47  match_number       70163 non-null  object
 48  team_runs          70163 non-null  int64
 49  team_balls         70163 non-null  int64
 50  team_wicket        70163 non-null  int64
 51  batter_runs        70163 non-null  int64
 52  batter_balls       70163 non-null  int64
 53  bowler_wicket      70163 non-null  int64
 54  batting_partners   70163 non-null  object
 55  striker_out        70163 non-null  bool
 56  phase              70163 non-null  object
 57  display_over       70163 non-null  int64
 58  is_boundary        70163 non-null  bool
 59  is_dot_ball        70163 non-null  bool
 60  is_bowler_wicket   70163 non-null  bool
dtypes: bool(5), datetime64[ns](1), float64(2), int64(25), object(28)
memory usage: 30.3+ MB

In [ ]:
ball_by_ball.head()

,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,...,batter_runs,batter_balls,bowler_wicket,batting_partners,striker_out,phase,display_over,is_boundary,is_dot_ball,is_bowler_wicket
0,1304047,2022-03-26,T20,Indian Premier League,1,Chennai Super Kings,Kolkata Knight Riders,0,1,0.1,...,0,1,0,"('DP Conway', 'RD Gaikwad')",False,Powerplay,1,False,False,False
1,1304047,2022-03-26,T20,Indian Premier League,1,Chennai Super Kings,Kolkata Knight Riders,0,1,0.1,...,0,2,0,"('DP Conway', 'RD Gaikwad')",False,Powerplay,1,False,True,False
2,1304047,2022-03-26,T20,Indian Premier League,1,Chennai Super Kings,Kolkata Knight Riders,0,2,0.2,...,0,2,0,"('DP Conway', 'RD Gaikwad')",False,Powerplay,1,False,False,False
3,1304047,2022-03-26,T20,Indian Premier League,1,Chennai Super Kings,Kolkata Knight Riders,0,2,0.2,...,0,3,0,"('DP Conway', 'RD Gaikwad')",False,Powerplay,1,False,True,False
4,1304047,2022-03-26,T20,Indian Premier League,1,Chennai Super Kings,Kolkata Knight Riders,0,3,0.3,...,0,4,1,"('DP Conway', 'RD Gaikwad')",True,Powerplay,1,False,True,True

In [ ]:
ball_by_ball.to_csv(
    'ball_by_ball.csv',
    index=False
)

# Table 2- match_summary

In [ ]:
match_summary = (
    ball_by_ball[
        [
            'match_id',
            'date',
            'season',
            'venue',
            'city',
            'stage',
            'toss_winner',
            'toss_decision',
            'match_won_by',
            'player_of_match',
            'win_outcome',
            'result_type',
            'method'
        ]
    ]
    .drop_duplicates()
)

In [ ]:
teams = (
    ball_by_ball.groupby('match_id')['batting_team']
    .unique()
    .reset_index()
)

teams['team_count'] = teams['batting_team'].apply(len)

In [ ]:
teams = teams[teams['team_count'] == 2]

In [ ]:
teams['team1'] = teams['batting_team'].apply(
    lambda x: x[0]
)

teams['team2'] = teams['batting_team'].apply(
    lambda x: x[1]
)

In [ ]:
teams = teams[['match_id', 'team1', 'team2']]

match_summary = match_summary.merge(
    teams,
    on='match_id',
    how='inner'
)

In [ ]:
match_summary['match_id'].nunique()

290

Creating inning score table:

In [ ]:
# it captures total runs scored in each innings

innings_score = (
    ball_by_ball.groupby(
        ['match_id', 'innings']
    )['runs_total']
    .sum()
    .reset_index()
)

In [ ]:

# Pivot converts row values --> columns


innings_pivot = (
    innings_score.pivot(
        index='match_id',
        columns='innings',
        values='runs_total'
    )
    .reset_index()
)

In [ ]:
innings_pivot.columns  # here 3, 4 are the super over innings

Index(['match_id', 1, 2, 3, 4], dtype='object', name='innings')

In [ ]:
innings_pivot = innings_pivot[
    ['match_id', 1, 2]
]

In [ ]:
innings_pivot.columns = [
    'match_id',
    'innings1_score',
    'innings2_score'
]

In [ ]:
# Merge scorres - ignoring super oper for now

match_summary = match_summary.merge(
    innings_pivot,
    on='match_id',
    how='left'
)

In [ ]:
innings_pivot.columns

Index(['match_id', 'innings1_score', 'innings2_score'], dtype='object')

In [ ]:
match_summary.columns

Index(['match_id', 'date', 'season', 'venue', 'city', 'stage', 'toss_winner',
       'toss_decision', 'match_won_by', 'player_of_match', 'win_outcome',
       'result_type', 'method', 'team1', 'team2', 'innings1_score',
       'innings2_score'],
      dtype='object')

In [ ]:
# chase vs defend
import numpy as np

match_summary['win_type'] = np.where(
    match_summary['innings2_score'] >
    match_summary['innings1_score'],

    'Chased',

    'Defended'
)

In [ ]:
# toss advantage

match_summary['toss_match_same_winner'] = np.where(
    match_summary['toss_winner'] ==
    match_summary['match_won_by'],

    'Yes',

    'No'
)

In [ ]:
match_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   match_id                290 non-null    int64
 1   date                    290 non-null    datetime64[ns]
 2   season                  290 non-null    int64
 3   venue                   290 non-null    object
 4   city                    290 non-null    object
 5   stage                   290 non-null    object
 6   toss_winner             290 non-null    object
 7   toss_decision           290 non-null    object
 8   match_won_by            290 non-null    object
 9   player_of_match         290 non-null    object
 10  win_outcome             288 non-null    object
 11  result_type             2 non-null      object
 12  method                  3 non-null      object
 13  team1                   290 non-null    object
 14  team2                   290 non-null    object
 15  innings1_score          290 non-null    float64
 16  innings2_score          290 non-null    float64
 17  win_type                290 non-null    object
 18  toss_match_same_winner  290 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(2), object(14)
memory usage: 43.2+ KB

In [ ]:
match_summary.head()

,match_id,date,season,venue,city,stage,toss_winner,toss_decision,match_won_by,player_of_match,win_outcome,result_type,method,team1,team2,innings1_score,innings2_score,win_type,toss_match_same_winner
0,1304047,2022-03-26,2022,"Wankhede Stadium, Mumbai",Mumbai,Unknown,Kolkata Knight Riders,field,Kolkata Knight Riders,UT Yadav,6 wickets,NaN,NaN,Chennai Super Kings,Kolkata Knight Riders,131.0,133.0,Chased,Yes
1,1304048,2022-03-27,2022,"Brabourne Stadium, Mumbai",Mumbai,Unknown,Delhi Capitals,field,Delhi Capitals,Kuldeep Yadav,4 wickets,NaN,NaN,Mumbai Indians,Delhi Capitals,177.0,179.0,Chased,Yes
2,1304049,2022-03-27,2022,"Dr DY Patil Sports Academy, Mumbai",Mumbai,Unknown,Punjab Kings,field,Punjab Kings,OF Smith,5 wickets,NaN,NaN,Royal Challengers Bengaluru,Punjab Kings,205.0,208.0,Chased,Yes
3,1304050,2022-03-28,2022,"Wankhede Stadium, Mumbai",Mumbai,Unknown,Gujarat Titans,field,Gujarat Titans,Mohammed Shami,5 wickets,NaN,NaN,Lucknow Super Giants,Gujarat Titans,158.0,161.0,Chased,Yes
4,1304051,2022-03-29,2022,"Maharashtra Cricket Association Stadium, Pune",Pune,Unknown,Sunrisers Hyderabad,field,Rajasthan Royals,SV Samson,61 runs,NaN,NaN,Rajasthan Royals,Sunrisers Hyderabad,210.0,149.0,Defended,No

In [ ]:
# exporting match_summary csv file.

match_summary.to_csv(
    'match_summary.csv',
    index=False
)

# Table 3 : Batter_stat

In [ ]:
batter_stat = (
    ball_by_ball.groupby(
        [
            'match_id',
            'season',
            'batting_team',
            'batter'
        ]
    )
    .agg(
        runs=('runs_batter', 'sum'),

        balls=('valid_ball', 'sum'),

        fours=('runs_batter',
               lambda x: (x == 4).sum()),

        sixes=('runs_batter',
               lambda x: (x == 6).sum()),

        dismissals=('player_out',
                     lambda x: x.notnull().sum())
    )
    .reset_index()
)

In [ ]:
# Strike rate

batter_stat['strike_rate'] = (
    batter_stat['runs']
    / batter_stat['balls']
) * 100

In [ ]:
# Boundary runs

batter_stat['boundary_runs'] = (
    batter_stat['fours'] * 4
    +
    batter_stat['sixes'] * 6
)

In [ ]:
#boundary percentage
batter_stat['boundary_pct'] = np.where(
    batter_stat['runs'] > 0,

    (batter_stat['boundary_runs']
     / batter_stat['runs']) * 100,

    0
)

In [ ]:
batter_stat['fifty'] = (
    batter_stat['runs'] >= 50
)

In [ ]:
batter_stat['century'] = (
    batter_stat['runs'] >= 100
)

In [ ]:
batter_stat.head()

,match_id,season,batting_team,batter,runs,balls,fours,sixes,dismissals,strike_rate,boundary_runs,boundary_pct,fifty,century
0,1304047,2022,Chennai Super Kings,AT Rayudu,15,17,1,1,0,88.235294,10,66.666667,False,False
1,1304047,2022,Chennai Super Kings,DP Conway,3,8,0,0,1,37.500000,0,0.000000,False,False
2,1304047,2022,Chennai Super Kings,MS Dhoni,50,37,7,1,0,135.135135,34,68.000000,True,False
3,1304047,2022,Chennai Super Kings,RA Jadeja,26,28,0,1,1,92.857143,6,23.076923,False,False
4,1304047,2022,Chennai Super Kings,RD Gaikwad,0,3,0,0,1,0.000000,0,0.000000,False,False

In [ ]:
batter_stat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4567 entries, 0 to 4566
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   match_id       4567 non-null   int64
 1   season         4567 non-null   int64
 2   batting_team   4567 non-null   object
 3   batter         4567 non-null   object
 4   runs           4567 non-null   int64
 5   balls          4567 non-null   int64
 6   fours          4567 non-null   int64
 7   sixes          4567 non-null   int64
 8   dismissals     4567 non-null   int64
 9   strike_rate    4565 non-null   float64
 10  boundary_runs  4567 non-null   int64
 11  boundary_pct   4567 non-null   float64
 12  fifty          4567 non-null   bool
 13  century        4567 non-null   bool
dtypes: bool(2), float64(2), int64(8), object(2)
memory usage: 437.2+ KB

In [ ]:
batter_stat.sort_values(
    by='runs',
    ascending=False
).head(10)

,match_id,season,batting_team,batter,runs,balls,fours,sixes,dismissals,strike_rate,boundary_runs,boundary_pct,fifty,century
3871,1473464,2025,Sunrisers Hyderabad,Abhishek Sharma,141,54,14,10,1,261.111111,116,82.269504,True,True
1043,1304112,2022,Lucknow Super Giants,Q de Kock,140,70,10,10,0,200.000000,100,71.428571,True,True
2304,1370352,2023,Gujarat Titans,Shubman Gill,129,59,7,10,1,218.644068,88,68.217054,True,True
1844,1359516,2023,Rajasthan Royals,YBK Jaiswal,124,61,16,8,1,203.278689,112,90.322581,True,True
2933,1426277,2024,Lucknow Super Giants,MP Stoinis,124,61,13,6,0,203.278689,88,70.967742,True,True
4480,1473507,2025,Lucknow Super Giants,RR Pant,118,61,11,8,0,193.442623,92,77.966102,True,True
4409,1473502,2025,Lucknow Super Giants,MR Marsh,117,64,10,8,1,182.812500,88,75.213675,True,True
530,1304080,2022,Rajasthan Royals,JC Buttler,116,65,9,9,1,178.461538,90,77.586207,True,True
2619,1422137,2024,Royal Challengers Bengaluru,V Kohli,113,72,12,4,0,156.944444,72,63.716814,True,True
1127,1312198,2022,Royal Challengers Bengaluru,RM Patidar,112,53,12,7,0,211.320755,90,80.357143,True,True

In [ ]:
batter_stat.to_csv(
    'batter_stat.csv',
    index=False
)

# Bowler_stat

In [ ]:
bowler_stat = (
    ball_by_ball.groupby(
        [
            'match_id',
            'season',
            'bowling_team',
            'bowler'
        ]
    )
    .agg(
        balls=('valid_ball', 'sum'),

        runs_conceded=('runs_total', 'sum'),

        wickets=('is_bowler_wicket', 'sum'),

        dot_balls=('is_dot_ball', 'sum')
    )
    .reset_index()
)

In [ ]:
# Over bowled

bowler_stat['overs'] = (
    bowler_stat['balls'] / 6
)

In [ ]:
bowler_stat['economy'] = (
    bowler_stat['runs_conceded']
    / bowler_stat['overs']
)

In [ ]:
bowler_stat['economy'] = np.where(
    bowler_stat['overs'] > 0,

    bowler_stat['runs_conceded']
    / bowler_stat['overs'],

    0
)

In [ ]:
bowler_stat['dot_ball_pct'] = np.where(
    bowler_stat['balls'] > 0,

    (bowler_stat['dot_balls']
     / bowler_stat['balls']) * 100,

    0
)

In [ ]:
bowler_stat['bowling_average'] = np.where(
    bowler_stat['wickets'] > 0,

    bowler_stat['runs_conceded']
    / bowler_stat['wickets'],

    0
)

In [ ]:
bowler_stat['three_wicket_haul'] = (
    bowler_stat['wickets'] >= 3
)

In [ ]:
bowler_stat['five_wicket_haul'] = (
    bowler_stat['wickets'] >= 5
)

In [ ]:
bowler_stat.head()

,match_id,season,bowling_team,bowler,balls,runs_conceded,wickets,dot_balls,overs,economy,dot_ball_pct,bowling_average,three_wicket_haul,five_wicket_haul
0,1304047,2022,Chennai Super Kings,AF Milne,15,19,0,9,2.5,7.60,60.000000,0.000000,False,False
1,1304047,2022,Chennai Super Kings,DJ Bravo,24,20,3,11,4.0,5.00,45.833333,6.666667,True,False
2,1304047,2022,Chennai Super Kings,MJ Santner,24,31,1,5,4.0,7.75,20.833333,31.000000,False,False
3,1304047,2022,Chennai Super Kings,RA Jadeja,24,25,0,8,4.0,6.25,33.333333,0.000000,False,False
4,1304047,2022,Chennai Super Kings,S Dube,6,15,0,0,1.0,15.00,0.000000,0.000000,False,False

In [ ]:
bowler_stat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3480 entries, 0 to 3479
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           3480 non-null   int64
 1   season             3480 non-null   int64
 2   bowling_team       3480 non-null   object
 3   bowler             3480 non-null   object
 4   balls              3480 non-null   int64
 5   runs_conceded      3480 non-null   int64
 6   wickets            3480 non-null   int64
 7   dot_balls          3480 non-null   int64
 8   overs              3480 non-null   float64
 9   economy            3480 non-null   float64
 10  dot_ball_pct       3480 non-null   float64
 11  bowling_average    3480 non-null   float64
 12  three_wicket_haul  3480 non-null   bool
 13  five_wicket_haul   3480 non-null   bool
dtypes: bool(2), float64(4), int64(6), object(2)
memory usage: 333.2+ KB

In [ ]:
bowler_stat.sort_values(
    by='wickets',
    ascending=False
).head(10)

,match_id,season,bowling_team,bowler,balls,runs_conceded,wickets,dot_balls,overs,economy,dot_ball_pct,bowling_average,three_wicket_haul,five_wicket_haul
2008,1422139,2024,Lucknow Super Giants,Yash Thakur,23,31,5,13,3.833333,8.086957,56.521739,6.2,True,True
1726,1370351,2023,Mumbai Indians,Akash Madhwal,21,6,5,16,3.500000,1.714286,76.190476,1.2,True,True
351,1304076,2022,Rajasthan Royals,YS Chahal,24,40,5,7,4.000000,10.000000,29.166667,8.0,True,True
621,1304100,2022,Royal Challengers Bengaluru,PWH de Silva,24,19,5,13,4.000000,4.750000,54.166667,3.8,True,True
1609,1359536,2023,Sunrisers Hyderabad,B Kumar,24,31,5,10,4.000000,7.750000,41.666667,6.2,True,True
2046,1426263,2024,Mumbai Indians,JJ Bumrah,24,22,5,12,4.000000,5.500000,50.000000,4.4,True,True
889,1359477,2023,Lucknow Super Giants,MA Wood,24,14,5,17,4.000000,3.500000,70.833333,2.8,True,True
2206,1426276,2024,Rajasthan Royals,Sandeep Sharma,24,18,5,13,4.000000,4.500000,54.166667,3.6,True,True
647,1304102,2022,Mumbai Indians,JJ Bumrah,24,10,5,18,4.000000,2.500000,75.000000,2.0,True,True
2724,1473447,2025,Delhi Capitals,MA Starc,22,35,5,12,3.666667,9.545455,54.545455,7.0,True,True

In [ ]:
bowler_stat.to_csv(
    'bowler_stat.csv',
    index=False
)

# Team_performance

In [ ]:
team_matches = pd.concat([

    match_summary[['match_id', 'team1']]
    .rename(columns={'team1': 'team'}),

    match_summary[['match_id', 'team2']]
    .rename(columns={'team2': 'team'})

])

In [ ]:
matches_played = (
    team_matches.groupby('team')
    .agg(
        matches_played=('match_id', 'nunique')
    )
    .reset_index()
)

In [ ]:
matches_won = (
    match_summary.groupby('match_won_by')
    .agg(
        matches_won=('match_id', 'count')
    )
    .reset_index()
    .rename(columns={'match_won_by': 'team'})
)

In [ ]:
team_performance = matches_played.merge(
    matches_won,
    on='team',
    how='left'
)

In [ ]:
team_performance['matches_won'] = (
    team_performance['matches_won']
    .fillna(0)
)

In [ ]:
team_performance['win_pct'] = (
    team_performance['matches_won']
    / team_performance['matches_played']
) * 100

In [ ]:
# Here, team run calculating

team_runs = (
    ball_by_ball.groupby('batting_team')
    .agg(
        total_runs=('runs_total', 'sum')
    )
    .reset_index()
    .rename(columns={'batting_team': 'team'})
)

In [ ]:
team_wickets = (
    ball_by_ball.groupby('bowling_team')
    .agg(
        total_wickets=('is_bowler_wicket', 'sum')
    )
    .reset_index()
    .rename(columns={'bowling_team': 'team'})
)

In [ ]:
team_fours = (
    ball_by_ball[
        ball_by_ball['runs_batter'] == 4   # chauka
    ]
    .groupby('batting_team')
    .size()
    .reset_index(name='fours')
    .rename(columns={'batting_team': 'team'})
)

In [ ]:
team_sixes = (
    ball_by_ball[
        ball_by_ball['runs_batter'] == 6    # for chakka
    ]
    .groupby('batting_team')
    .size()
    .reset_index(name='sixes')
    .rename(columns={'batting_team': 'team'})
)

In [ ]:
team_performance = (
    team_performance
    .merge(team_runs, on='team', how='left')
    .merge(team_wickets, on='team', how='left')
    .merge(team_fours, on='team', how='left')
    .merge(team_sixes, on='team', how='left')
)

In [ ]:
team_performance = (
    team_performance.fillna(0)
)

In [ ]:
team_performance.head()

,team,matches_played,matches_won,win_pct,total_runs,total_wickets,fours,sixes
0,Chennai Super Kings,57,25,43.859649,9965,339,789,445
1,Delhi Capitals,55,25,45.454545,9596,323,865,418
2,Gujarat Titans,60,37,61.666667,10649,362,947,395
3,Kolkata Knight Riders,55,28,50.909091,9355,335,790,480
4,Lucknow Super Giants,57,30,52.631579,10242,324,795,484

In [ ]:
team_performance.sort_values(
    by='matches_won',
    ascending=False
)

,team,matches_played,matches_won,win_pct,total_runs,total_wickets,fours,sixes
2,Gujarat Titans,60,37,61.666667,10649,362,947,395
8,Royal Challengers Bengaluru,60,34,56.666667,10717,350,892,499
7,Rajasthan Royals,60,30,50.000000,10623,330,913,507
4,Lucknow Super Giants,57,30,52.631579,10242,324,795,484
6,Punjab Kings,59,28,47.457627,10648,336,907,526
3,Kolkata Knight Riders,55,28,50.909091,9355,335,790,480
5,Mumbai Indians,60,26,43.333333,10642,357,913,516
0,Chennai Super Kings,57,25,43.859649,9965,339,789,445
1,Delhi Capitals,55,25,45.454545,9596,323,865,418
9,Sunrisers Hyderabad,57,25,43.859649,10144,310,822,479

In [ ]:
team_performance.to_csv(
    'team_performance.csv',
    index=False
)